/*
UCS compatibility patch!
0 = Disabled disregarding if its detects UCS by Enginseer.
1 = Enabled if it detects the UCS by Enginseer.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('COLORS-UCS', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'COLORS-UCS' AND EXISTS (SELECT * FROM MinorCivilizations WHERE Type='MINOR_CIV_HONDURAS') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 0);

-- Main Compatibility Code
	-- defining new color schemes for minors
	-- 1st part
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_NANMANDOL',		0.8,		0.474,		0.780,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_CLERMONT',		0.905,		0.153,		0.153,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_GRANADA',		1,			0.365,		0.365,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_MUSCAT',		1,			0.969,		0.282,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_HONDURAS',		1,			0.663,		0.176,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_ARMAGH',		0.184,		0.824,		0.776,		1
	
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_AUCKLAND',		0.020,		0.424,		0.207,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 2nd part
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_GWYNEDD',		0.8,		0.475,		0.780,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_MUISCA',		1,			0.767,		0.420,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_LACONIA',		0.521,		0.157,		0.157,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_CHEVAK',		0.4,		0.8,		0,			1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_SANTO_DOMINGO',	1,			0.835,		0.588,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_MANAGUA',		0.878,		0.596,		0.165,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_ODENSO',		0.627,		0.455,		0.227,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_YANGCHENG',		0.227,		0.667,		0.671,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_PHANOTEUS',		1,			0.106,		0.106,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_DOUALA',		1,			1,			0.6,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 3rd part
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_SIERRA_LEONE',	0.596,		0.345,		0.894,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_NAIROBI',		0.478,		0.898,		0.172,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_QUELIMANE',		1,			0.415,		0,			1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_KIGALI',		0.992,		0.607,		0.337,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_DJIBOUTI',		0.937,		0.851,		0.015,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_AMBRACIA',		0.749,		0.078,		0.106,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_DODOMA',		0.925,		0.231,		0.231,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_FAYA',			0.588,		0.369,		0.082,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO Colors 
				(Type, 								Red, 		Green, 		Blue, 		Alpha)
	SELECT		'COLOR_PLAYER_MINOR_SURREY',		1,			0.341,		0.227,		1
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- defining whole minor schemes
	-- 1st part
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_NANMANDOL',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_NANMANDOL',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_CLERMONT',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_CLERMONT',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_GRANADA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_GRANADA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_MUSCAT',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MUSCAT',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_HONDURAS',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_HONDURAS',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_ARMAGH',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ARMAGH',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_AUCKLAND',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AUCKLAND',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 2nd part
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_GWYNEDD',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_GWYNEDD',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_MUISCA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MUISCA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_LACONIA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_LACONIA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_CHEVAK',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_CHEVAK',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_SANTO_DOMINGO',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SANTO_DOMINGO',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_MANAGUA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_MANAGUA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_ODENSO',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_ODENSO',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_YANGCHENG',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_YANGCHENG',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_PHANOTEUS',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_PHANOTEUS',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_DOUALA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DOUALA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 3rd part
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_SIERRA_LEONE',	'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SIERRA_LEONE',	'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_NAIROBI',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_NAIROBI',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_QUELIMANE',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_QUELIMANE',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_KIGALI',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_KIGALI',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_DJIBOUTI',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DJIBOUTI',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_AMBRACIA',		'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_AMBRACIA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_DODOMA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_DODOMA',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_FAYA',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_FAYA',			'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	INSERT INTO PlayerColors 
				(Type, 								PrimaryColor, 					SecondaryColor, 					TextColor)
	SELECT		'PLAYERCOLOR_MINOR_SURREY',			'COLOR_PLAYER_MINOR_ICON',		'COLOR_PLAYER_MINOR_SURREY',		'COLOR_PLAYER_PEACH_TEXT'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- updating color scheme for minor civs
	-- 1st part
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_NANMANDOL' WHERE Type = 'MINOR_CIV_NANMANDOL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CLERMONT' WHERE Type = 'MINOR_CIV_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_GRANADA' WHERE Type = 'MINOR_CIV_GRANADA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MUSCAT' WHERE Type = 'MINOR_CIV_MUSCAT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_HONDURAS' WHERE Type = 'MINOR_CIV_HONDURAS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ARMAGH' WHERE Type = 'MINOR_CIV_ARMAGH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AUCKLAND' WHERE Type = 'MINOR_CIV_AUCKLAND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 2nd part
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_GWYNEDD' WHERE Type = 'MINOR_CIV_GWYNEDD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MUISCA' WHERE Type = 'MINOR_CIV_MUISCA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_LACONIA' WHERE Type = 'MINOR_CIV_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CHEVAK' WHERE Type = 'MINOR_CIV_CHEVAK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SANTO_DOMINGO' WHERE Type = 'MINOR_CIV_SANTO_DOMINGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MANAGUA' WHERE Type = 'MINOR_CIV_MANAGUA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_ODENSO' WHERE Type = 'MINOR_CIV_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_YANGCHENG' WHERE Type = 'MINOR_CIV_YANGCHENG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PHANOTEUS' WHERE Type = 'MINOR_CIV_PHANOTEUS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DOUALA' WHERE Type = 'MINOR_CIV_DOUALA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	
	-- 3rd part
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SIERRA_LEONE' WHERE Type = 'MINOR_CIV_SIERRA_LEONE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_NAIROBI' WHERE Type = 'MINOR_CIV_NAIROBI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_QUELIMANE' WHERE Type = 'MINOR_CIV_QUELIMANE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_KIGALI' WHERE Type = 'MINOR_CIV_KIGALI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DJIBOUTI' WHERE Type = 'MINOR_CIV_DJIBOUTI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_AMBRACIA' WHERE Type = 'MINOR_CIV_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_DODOMA' WHERE Type = 'MINOR_CIV_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_FAYA' WHERE Type = 'MINOR_CIV_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);
	UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_SURREY' WHERE Type = 'MINOR_CIV_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COLORS-UCS' AND Value= 1);