


INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
  SELECT Type, 'PROMOTION_XP_FOR_SCOUTING_II' FROM Units WHERE Type='UNIT_EXPLORERX';
CREATE TRIGGER FreeXpForScouting2
AFTER INSERT ON Units
WHEN 'UNIT_EXPLORERX'=NEW.Type
BEGIN
  INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
    VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING_II');
END;


INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
  SELECT Type, 'PROMOTION_XP_FOR_SCOUTING_III' FROM Units WHERE Type='UNIT_ADVENTURER';
CREATE TRIGGER FreeXpForScouting3
AFTER INSERT ON Units
WHEN 'UNIT_ADVENTURER'=NEW.Type
BEGIN
  INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
    VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING_III');
END;


INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
  SELECT Type, 'PROMOTION_XP_FOR_SCOUTING_IV' FROM Units WHERE Type='UNIT_AIRSHIP';
CREATE TRIGGER FreeXpForScouting4
AFTER INSERT ON Units
WHEN 'UNIT_AIRSHIP'=NEW.Type
BEGIN
  INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
    VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING_IV');
END;


INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
  SELECT Type, 'PROMOTION_XP_FOR_SCOUTING_V' FROM Units WHERE Type='UNIT_SKY_FORTRESS';
CREATE TRIGGER FreeXpForScouting5
AFTER INSERT ON Units
WHEN 'UNIT_SKY_FORTRESS'=NEW.Type
BEGIN
  INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
    VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING_V');
END;


	
-- Update any additional recon units to have PROMOTION_XP_FOR_SCOUTING as well
CREATE TRIGGER FreeXpForScouting
AFTER INSERT ON Units
WHEN ('UNITCOMBAT_RECON'=NEW.CombatClass AND NOT 'UNIT_EXPLORERX'=NEW.Type AND NOT 'UNIT_ADVENTURER'=NEW.Type AND NOT 'UNIT_AIRSHIP'=NEW.Type AND NOT 'UNIT_SKY_FORTRESS'=NEW.Type)
BEGIN
  INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
    VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING');
END;

-- Give all recon units PROMOTION_XP_FOR_SCOUTING
INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
  SELECT Type, 'PROMOTION_XP_FOR_SCOUTING' FROM Units WHERE CombatClass='UNITCOMBAT_RECON' AND NOT Type='UNIT_EXPLORERX' AND NOT Type='UNIT_ADVENTURER' AND NOT Type='UNIT_AIRSHIP' AND NOT Type='UNIT_SKY_FORTRESS';
